name: shelf_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  shelf_cors_headers: ^0.1.5
  dotenv: ^4.2.0
  dart_jsonwebtoken: ^3.2.0
  shelf_router: ^1.1.4
  http: ^1.5.0
  mongo_dart: ^0.10.5
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
